[package]
name = gentoo_portage
title = Gentoo Portage
author = Marcel Pennewiss <opensource@pennewiss.de>
description = This plugin checks for available updates (including new slots) and unpatched security advisories using portage python libraries.

# CheckMK Compatibility
version.min_required = 2.4.0b1
version.packaged = 2.4.0p32
version.usable_until = 

# Optional settings
download_url = https://github.com/mape2k/check_mk_extensions

# Build Options
validate_python = true
