[package]
name = proxmox_backup_server
title = Proxmox Backup Server
author = Marcel Pennewiss <opensource@pennewiss.de>
description = This agent plugin checks datastores, task summary (of the last day) as well as prune, sync and verify jobs from Proxmox Backup server.

# CheckMK Compatibility
version.min_required = 2.4.0b1
version.packaged = 2.4.0p25
version.usable_until = 

# Optional settings
download_url = https://github.com/mape2k/check_mk_extensions

# Build Options
validate_python = true
