[package]
name = lnx_backup
title = Linux backups (rsync, tar, duply)
author = Marcel Pennewiss <opensource@pennewiss.de>
description = Check result of linux based backups with rsync, tar and duply

# CheckMK Compatibility
version.min_required = 2.3.0b1
version.packaged = 2.4.0p25
version.usable_until = 

# Optional settings
download_url = https://github.com/mape2k/check_mk_extensions

# Build Options
validate_python = true
