[package]
name = proxmox_ve
title = Proxmox VE
author = Marcel Pennewiss <opensource@pennewiss.de>
description = This agent plugin runs Proxmox VE special agent compatible checks via check_mk_agent.

# CheckMK Compatibility
version.min_required = 2.4.0b1
version.packaged = 2.4.0p35
version.usable_until = 

# Optional settings
download_url = https://github.com/mape2k/check_mk_extensions

# Build Options
validate_python = true