[package]
name = exim_mailq
title = Exim Queue
author = Marcel Pennewiss <opensource@pennewiss.de>
description = Check the exim mail queue

# CheckMK Compatibility
version.min_required = 2.3.0b1
version.packaged = 2.4.0p25
version.usable_until = 

# Optional settings
download_url = https://github.com/mape2k/check_mk_extensions

# Build Options
validate_python = true
